# Travis CI for OpenCNN
#
# Copyright 2019. All Rights Reserved.
# Author: csukuangfj@gmail.com (Fangjun Kuang)
# Date: November 26, 2018
#

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

env:
  - CXX_FLAGS=-std=c++11

# https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - git

notifications:
  email: false

sudo: false

script:
    - bash travis/script.sh
